#!/usr/bin/env bash
#
# sync-from-handoff.sh — import a Claude Design handoff into this repo.
#
# The design tool (claude.ai/design) and this repo are two sources of truth.
# This script keeps the *design-owned* files in sync with a handoff export
# while never clobbering *repo-owned* files (README, SKILL, lint config) and
# never re-adding pruned scratch (uploads screenshots, scraps, prompt notes).
#
# See SYNC.md for the ownership boundary and the full procedure.
#
# Usage:
#   scripts/sync-from-handoff.sh <handoff.tar.gz | extracted-dir | .../project>
#
# It is idempotent: re-running with the same handoff produces no changes.
# After it runs, review the diff, update README.md / SKILL.md by hand if the
# design intent changed, then open a PR.

set -euo pipefail

# ---- locate inputs ----------------------------------------------------------
SRC="${1:-}"
if [[ -z "$SRC" ]]; then
  echo "usage: $0 <handoff.tar.gz | extracted-dir | .../project>" >&2
  exit 2
fi

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
TMP=""
cleanup() { [[ -n "$TMP" && -d "$TMP" ]] && rm -rf "$TMP"; }
trap cleanup EXIT

if [[ -f "$SRC" ]]; then
  TMP="$(mktemp -d)"
  echo "→ extracting $SRC"
  tar -xzf "$SRC" -C "$TMP"
  SRC="$TMP"
fi

# Resolve to the project/ dir that holds colors_and_type.css.
PROJECT=""
if [[ -f "$SRC/colors_and_type.css" ]]; then
  PROJECT="$SRC"
else
  PROJECT="$(find "$SRC" -type f -name colors_and_type.css -printf '%h\n' 2>/dev/null | head -1)"
fi
if [[ -z "$PROJECT" || ! -d "$PROJECT" ]]; then
  echo "error: could not find the design project/ dir (no colors_and_type.css under $SRC)" >&2
  exit 1
fi
echo "→ design project: $PROJECT"
echo "→ repo:           $REPO_ROOT"

# ---- ownership rules --------------------------------------------------------
# Directories regenerated by the design tool: mirror exactly (with deletes),
# minus never-import scratch (*.prompt.md).
DESIGN_DIRS=(preview ui_kits review assets fonts)

# Mirror a directory src/ -> dst/ : copy every file (except *.prompt.md), then
# delete dst files that no longer exist in src. Portable (no rsync); handles
# spaces in filenames.
mirror_dir() {
  local src="$1" dst="$2"
  mkdir -p "$dst"
  # copy/update
  while IFS= read -r -d '' f; do
    local rel="${f#"$src"/}"
    case "$rel" in *.prompt.md) continue ;; esac
    mkdir -p "$dst/$(dirname "$rel")"
    cp "$f" "$dst/$rel"
  done < <(find "$src" -type f -print0)
  # delete files removed upstream
  while IFS= read -r -d '' f; do
    local rel="${f#"$dst"/}"
    case "$rel" in *.prompt.md) continue ;; esac
    [[ -f "$src/$rel" ]] || rm -f "$f"
  done < <(find "$dst" -type f -print0)
}

# Individual design-owned files at the project root: overwrite if present.
DESIGN_FILES=(
  "colors_and_type.css"
  "primereact-connecta.css"
  "styles.css"
  "_ds_manifest.json"
  "_ds_bundle.js"
  ".thumbnail"
  "Connecta Design System - Guide.html"
  "Connecta × PrimeReact.html"
)

# Repo-owned (NEVER overwritten by import): README.md SKILL.md
#   _adherence.oxlintrc.json scripts/ SYNC.md .github/ .git/
# Never-import (skipped even if present in the handoff): uploads/* scraps/*
#   *.prompt.md  "Connecta DS - Overview & Cleanup.html"  stale root bundles.

# ---- mirror design dirs -----------------------------------------------------
for d in "${DESIGN_DIRS[@]}"; do
  if [[ -d "$PROJECT/$d" ]]; then
    echo "→ sync dir: $d/"
    mirror_dir "$PROJECT/$d" "$REPO_ROOT/$d"
  fi
done

# ---- copy design root files -------------------------------------------------
for f in "${DESIGN_FILES[@]}"; do
  if [[ -f "$PROJECT/$f" ]]; then
    cp "$PROJECT/$f" "$REPO_ROOT/$f"
    echo "→ sync file: $f"
  fi
done

# ---- report -----------------------------------------------------------------
echo
echo "=== residual design drift (handoff vs repo; should be empty) ==="
DRIFT=0
while IFS= read -r rel; do
  case "$rel" in
    README.md|SKILL.md|_adherence.oxlintrc.json) continue ;;        # repo-owned
    uploads/*|scraps/*|*.prompt.md) continue ;;                     # never-import
    "Connecta DS - Overview & Cleanup.html") continue ;;            # retired
  esac
  if [[ -f "$REPO_ROOT/$rel" ]]; then
    if ! diff -q "$PROJECT/$rel" "$REPO_ROOT/$rel" >/dev/null 2>&1; then
      echo "  DIFFERS: $rel"; DRIFT=1
    fi
  else
    echo "  MISSING in repo (intentional?): $rel"; DRIFT=1
  fi
done < <(cd "$PROJECT" && find . -type f | sed 's|^\./||' | sort)
[[ "$DRIFT" -eq 0 ]] && echo "  ✓ design source matches the handoff"

echo
echo "=== validate artifacts ==="
python3 - "$REPO_ROOT" <<'PY'
import json, os, sys
root = sys.argv[1]
m = json.load(open(os.path.join(root, "_ds_manifest.json")))
missing = [c["path"] for c in m["cards"] if not os.path.exists(os.path.join(root, c["path"]))]
print(f"  manifest: {len(m['cards'])} cards, {len(m.get('components',[]))} components; missing files: {missing or 'none'}")
groups = sorted({c["group"] for c in m["cards"]})
print(f"  groups: {groups}")
PY
if command -v node >/dev/null; then
  node --check "$REPO_ROOT/_ds_bundle.js" && echo "  bundle: node --check OK"
fi
# guard: design source must carry no legacy names
if grep -rliE 'tamagui|cosmo' "$REPO_ROOT/preview" "$REPO_ROOT/ui_kits" >/dev/null 2>&1; then
  echo "  ⚠ legacy term (tamagui/cosmo) found in synced design source — investigate"
fi

echo
echo "Done. Next: review 'git status', update README.md / SKILL.md by hand if the"
echo "design intent changed, then commit on a branch and open a PR (see SYNC.md)."
